spring:
    application:
        name: service-chat
    datasource:
        url: jdbc:mysql://localhost:3306/xhub_chat?serverTimezone=GMT%2B8
        username: root
        password:
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
server:
    port: 9000